image: makeorg/docker-sbt-coursier

variables:
  CI_BUILD: "true"

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - docker
  before_script:
    - if [ ! -e /var/run/docker.sock ]; then DOCKER_DRIVER=vfs dockerd & fi
    - until docker ps; do echo "waiting for docker to be up..."; sleep 0.5; done
    - docker login "https://$NEXUS_URL" --username "$NEXUS_USER" --password "$NEXUS_PASSWORD"
  script:
    - sbt clean coverage test it:test
    - sbt coverageReport coverageAggregate
    - sbt clean publish

deploy:
  stage: deploy
  only:
    - master
  script:
    - >
      curl -D - -X "POST"
      -H "Accept: application/json"
      -H "Content-Type: application/x-www-form-urlencoded"
      -H "X-Rundeck-Auth-Token: $RUNDECK_TOKEN"
      --data-urlencode "argString=-tag 0.0.1-SNAPSHOT"
      http://rundeck.prod.makeorg.tech:4440/api/16/job/9132ebc2-19fb-452a-b6ee-3ac316fe053f/run
