image: makeorg/docker-sbt-coursier

variables:
  CI_BUILD: "true"
  SBT_OPTS: "-Xms2G -Xmx2G"
  IMAGE: "/repository/docker-dev/make-api"

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - docker
  before_script:
    - if [ ! -e /var/run/docker.sock ]; then DOCKER_DRIVER=vfs dockerd & fi
    - until docker ps; do echo "waiting for docker to be up..."; sleep 0.5; done
    - docker login "https://$NEXUS_URL" --username "$NEXUS_USER" --password "$NEXUS_PASSWORD"
    - docker pull docker.elastic.co/elasticsearch/elasticsearch:5.4.0
  script:
    - export IMAGE_VERSION=`date +"%Y-%m-%d"`-`git rev-parse --short HEAD`
    - sbt clean coverage test it:test
    - sbt coverageReport coverageAggregate
    - sbt clean publishLocal
    - docker push $NEXUS_URL$IMAGE:$CI_COMMIT_REF_NAME-$IMAGE_VERSION
    - docker tag $NEXUS_URL$IMAGE:$CI_COMMIT_REF_NAME-$IMAGE_VERSION $NEXUS_URL$IMAGE:$CI_COMMIT_REF_NAME-latest
    - docker push $NEXUS_URL$IMAGE:$CI_COMMIT_REF_NAME-latest

deploy:
  stage: deploy
  only:
    - master
  script:
    - >
      curl -D - -X "POST"
      -H "Accept: application/json"
      -H "Content-Type: application/x-www-form-urlencoded"
      -H "X-Rundeck-Auth-Token: $RUNDECK_TOKEN"
      --data-urlencode "argString=-version $CI_COMMIT_REF_NAME-latest"
      http://rundeck.preprod.makeorg.tech:4440/api/16/job/3d15510a-fa55-45dd-9cdb-6068808f11e4/run
