image: charafau/docker-sbt-scala

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - sbt test

deploy:
  stage: deploy
  script:
    - echo "Un jour mon appli se deploiera, un jour on l'utilisera !"
