image: makeorg/docker-sbt-coursier

stages:
  - build

build:
  stage: build
  tags:
    - docker
  before_script:
    - if [ ! -e /var/run/docker.sock ]; then dockerd --storage-driver=vfs & fi
    - docker login --username $NEXUS_USERNAME --password $NEXUS_PASSWORD
  script:
    - sbt clean coverage test
    - sbt coverageReport coverageAggregate
    - sbt publishLocal
  cache:
    paths:
      - /root/.coursier
      - /root/.ivy2
