image: charafau/docker-sbt-scala

variables:
  COURSIER_VERSION: 1.0.0-RC3

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - sbt test

deploy:
  stage: deploy
  script:
    - echo "Un jour mon appli se deploiera, un jour on l'utilisera !"
