version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      KAFKA_HEAP_OPTS: '-Xms128M -Xmx128M'
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 12181:2181
    networks:
      - makeapi
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    environment:
      KAFKA_HEAP_OPTS: '-Xms256M -Xmx256M'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_BROKER_ID: 42
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
      - 18081:8081
      - 10000:9000
    networks:
      - makeapi
    restart: on-failure:2
  schema_registry:
    image: confluentinc/cp-schema-registry:5.0.0
    depends_on:
      - kafka
    network_mode: service:kafka
    environment:
        SCHEMA_REGISTRY_HEAP_OPTS: '-Xms128M -Xmx128M'
        SCHEMA_REGISTRY_HOST_NAME: schema_registry
        SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181/kafka
        SCHEMA_REGISTRY_LISTENERS: http://kafka:8081
    restart: on-failure:2
  cockroach:
    image: cockroachdb/cockroach:v2.0.2
    command: start --insecure
    ports:
      - 26257:26257
      - 8080:8080
    networks:
      - makeapi
  cassandra:
    image: cassandra:3.10
    ports:
      - 7000:7000
      - 9042:9042
    environment:
      JVM_OPTS: '-Xms128M -Xmx128M'
    networks:
      - makeapi
  elasticsearch:
    image: makeorg/make-elasticsearch:6.3.0
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - makeapi
    environment:
      ES_JAVA_OPTS: '-Xms256M -Xmx512M'
      xpack.security.enabled: "false"
      http.host: elasticsearch
      transport.host: localhost
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200/_cluster/health"]
      interval: 5s
      timeout: 2s
      retries: 3
  semantic:
    image: nexus.prod.makeorg.tech/make-semantic:preproduction-latest
    ports:
      - 9001:9001
    environment:
      ES_URL: "elasticsearch:9200"
    depends_on:
      - elasticsearch
    networks:
      - makeapi
    restart: on-failure:5
  kafka-manager:
    image: sheepkiller/kafka-manager
    environment:
      ZK_HOSTS: zookeeper:2181
      KM_VERSION: 1.3.3.13
    network_mode: service:kafka
networks:
  makeapi:
    driver_opts:
      'com.docker.network.driver.mtu': 1450
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24

