version: '3'
services:
  zookeeper:
    image: zookeeper:3.4.10
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=localhost:2888:3888
    networks:
      - makeapi
  kafka:
    image: wurstmeister/kafka:0.10.2.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 42
    ports:
      - 9092:9092
      - 18081:8081
    networks:
      - makeapi
  schema_registry:
    image: cgswong/confluent-schema-registry:2.0.1
    depends_on:
      - kafka
    network_mode: service:kafka
    environment:
        ZOOKEEPER_PORT_2181_TCP_ADDR: zookeeper
        ZOOKEEPER_PORT_2181_TCP_PORT: 2181
    restart: on-failure:2
  cockroach:
    image: cockroachdb/cockroach:alpha-18828-g1227734
    command: start --insecure
    ports:
      - 26257:26257
    networks:
      - makeapi
  cassandra:
    image: cassandra:3.10
    ports:
      - 7000:7000
      - 9042:9042
    networks:
      - makeapi
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - makeapi
    environment:
      xpack.security.enabled: "false"
  consul:
    image: consul:0.8.3
    networks:
      - makeapi
    ports:
      - 8300:8300
      - 8301:8301
      - 8303:8302
      - 8500:8500
      - 8600:8600
networks:
  makeapi:
    ipam:
      driver: default
      config:
        - subnet: 20.0.0.0/24