version: '3'
services:
  api1:
    image: nexus.prod.makeorg.tech/repository/docker-dev/make-api:master-latest
    hostname: api1
    ports:
      - 9000:9000
      - 4000:4000
    environment:
      - TCP_HOST=api1
      - KAFKA_URI=kafka:9092
      - AVRO_REGISTRY_URL=http://schema-registry:8081
      - ES_URL=elasticsearch:9200
      - JDBC_URL=jdbc:postgresql://cockroach:26257/makeapi
      - ZOOKEEPER_URL=zookeeper:2181
      - CASSANDRA_0=cassandra
    networks:
      - makeapi
    depends_on:
      - zookeeper
      - kafka
      - cockroach
      - elasticsearch
      - cassandra
  api2:
    image: nexus.prod.makeorg.tech/repository/docker-dev/make-api:master-latest
    hostname: api2
    ports:
      - 19000:9000
      - 14000:4000
    environment:
      - TCP_HOST=api2
      - KAFKA_URI=kafka:9092
      - AVRO_REGISTRY_URL=http://schema-registry:8081
      - ES_URL=elasticsearch:9200
      - JDBC_URL=jdbc:postgresql://cockroach:26257/makeapi
      - ZOOKEEPER_URL=zookeeper:2181
      - CASSANDRA_0=cassandra
    networks:
      - makeapi
    depends_on:
      - zookeeper
      - kafka
      - cockroach
      - elasticsearch
      - cassandra
      - api1
  api3:
    image: nexus.prod.makeorg.tech/repository/docker-dev/make-api:master-latest
    hostname: api3
    ports:
      - 29000:9000
      - 24000:4000
    environment:
      - TCP_HOST=api3
      - KAFKA_URI=kafka:9092
      - AVRO_REGISTRY_URL=http://schema-registry:8081
      - ES_URL=elasticsearch:9200
      - JDBC_URL=jdbc:postgresql://cockroach:26257/makeapi
      - ZOOKEEPER_URL=zookeeper:2181
      - CASSANDRA_0=cassandra
    networks:
      - makeapi
    depends_on:
      - zookeeper
      - kafka
      - cockroach
      - elasticsearch
      - cassandra
      - api2
  elasticsearch:
    image: makeorg/make-elasticsearch:6.8.2
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - makeapi
    environment:
      ES_JAVA_OPTS: '-Xms256M -Xmx256M'
      xpack.security.enabled: "false"
      http.host: elasticsearch
      transport.host: localhost
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200/_cluster/health"]
      interval: 5s
      timeout: 2s
      retries: 3
  zookeeper:
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 12181:2181
    networks:
      - makeapi
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 42
    ports:
      - 9092:9092
      - 18081:8081
      - 10000:9000
    networks:
      - makeapi
    restart: on-failure:2
    depends_on:
      - zookeeper
  schema-registry:
    hostname: schema-registry
    image: confluentinc/cp-schema-registry:5.0.0
    depends_on:
      - kafka
    networks:
      - makeapi
    environment:
        SCHEMA_REGISTRY_HOST_NAME: schema-registry
        SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181/kafka
        SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
    restart: on-failure:3
  cockroach:
    image: cockroachdb/cockroach:v19.1.1
    hostname: cockroach
    command: start --insecure
    ports:
      - 26257:26257
    networks:
      - makeapi
  cassandra:
    image: cassandra:3.10
    hostname: cassandra
    ports:
      - 7000:7000
      - 9042:9042
    environment:
      JVM_OPTS: '-Xms256M -Xmx256M'
    networks:
      - makeapi
networks:
  makeapi:
    driver_opts:
      'com.docker.network.driver.mtu': 1450
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
