ALTER TABLE operation_of_question
    ADD COLUMN gradient_start STRING NOT NULL DEFAULT '#000000',
    ADD COLUMN gradient_end STRING NOT NULL DEFAULT '#000000',
    ADD COLUMN color STRING NOT NULL DEFAULT '#000000',
    ADD COLUMN footer_font_color STRING NOT NULL DEFAULT '#FFFFFF',
    ADD COLUMN description STRING(1024) NOT NULL DEFAULT '';

COMMIT;