BEGIN;

ALTER TABLE top_idea_comment ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NOW();
ALTER TABLE top_idea_comment ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NOW();

COMMIT;
