CREATE TABLE IF NOT EXISTS tag_type(
    id STRING(256) NOT NULL,
    label STRING(256) NULL,
    display STRING(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
    CONSTRAINT "primary" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS tag RENAME COLUMN slug TO id;

ALTER TABLE tag DROP COLUMN IF EXISTS enabled;

ALTER TABLE tag
    ADD COLUMN IF NOT EXISTS display STRING(64) NOT NULL DEFAULT 'INHERIT',
    ADD COLUMN IF NOT EXISTS tag_type_id STRING(256),
    ADD COLUMN IF NOT EXISTS operation_id STRING(256),
    ADD COLUMN IF NOT EXISTS theme_id STRING(256),
    ADD COLUMN IF NOT EXISTS weight FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS country STRING(10) NOT NULL DEFAULT 'FR',
    ADD COLUMN IF NOT EXISTS language STRING(10) NOT NULL DEFAULT 'fr';

CREATE INDEX ON tag (tag_type_id);
CREATE INDEX ON tag (operation_id);
CREATE INDEX ON tag (theme_id);

COMMIT;